on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
      - name: tag
        run: |
          git tag $TAG
          git push origin $TAG
        env:
          TAG: v${{ steps.package-version.outputs.current-version}}
